### ISSUE TITLE
Can we support flags that require no arguments?

### ISSUE THREAD

**Issue by bucaran** [fishery/getopts#11]
https://github.com/fisherman/fisherman/issues/84

**Comment by pickfire** [comment]
:+1:

**Comment by bucaran** [comment]
The problem is, to implement this the user would need to teach `getopts` that such and such option does **not** require arguments. `Getopts` design is supposed to be minimalistic. I deliberately wanted to avoid using an `optstring`, but maybe we can have the best of both worlds.

I'll ponder deeply.

**Comment by bucaran** [comment]
Closing as won't fix.
