### ISSUE TITLE
sed: invalid option -- E

### ISSUE THREAD

**Issue by lorenzoaws** [fishery/getopts#12]
On my RHEL5 box, I get an invalid usage error for sed (version 4.1.5)
```
Usage: sed [OPTION]... {script-only-if-no-other-script} [input-file]...
```
Based on http://blog.dmitryleskov.com/small-hacks/mysterious-gnu-sed-option-e/ it looks like `-r` is equivalent to `-E`

There was a similar issue reported and fixed in https://github.com/ndbroadbent/scm_breeze/issues/112  maybe the fix can be borrowed?

**Comment by bucaran** [comment]
Yes, AFIK `-r` == `-E`. 

The problem with that fix is that it needs to fork `sed` at least once just to determine the correct flag, instead we could just ship two versions of `getopts`, one that for RHEL5 (you are our first one :)) and another with -E , the present one.

**Comment by lorenzoaws** [comment]
Yes, we are a dying breed :) If you forked ```getopts``` would client scripts need to change their code to use one package or the other depending on their platform or would that be transparent?

**Comment by bucaran** [comment]
8629c44a6027f0d741a1335ad7c95d3eff1f4aab

I just pushed a new version implements getopts in Awk, without using sed :smile:

**Comment by lorenzoaws** [comment]
Thanks for the quick fix!
